[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "Extruder Principles and Operation"
authors = [{name = "bobolin", email = "1341979804@qq.com"}]
dynamic = ["version", "description"]
